import { css } from '@emotion/react'
import newStyled from '@emotion/styled'
import Head from 'next/head'

export default function Home() {
  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div css={bold}>Hello World</div>
    </Container>
  )
}

const Container = newStyled.div`
  background-color: pink;
`

const bold = css`
  font-weight: bold;
`
